version: '3'

services:
  anaconda3:
    image: anaconda:5.3.0
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/opt/notebooks
    # restart: always
    networks:
      backend:
    command:
      [
        '/opt/conda/bin/jupyter',
        'notebook',
        '--notebook-dir=/opt/notebooks',
        '--ip=0.0.0.0',
        '--port=8888',
        '--no-browser',
        '--allow-root',
      ]

networks:
  backend:
